version: '3.2'

services:
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
      container_name: elasticsearch
      ports:
         - "9200:9200"
      environment:
         - bootstrap.memory_lock=true
         - cluster.name=docker-cluster
         - cluster.routing.allocation.disk.threshold_enabled=false
         - discovery.type=single-node
         - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      volumes:
         - esdata:/usr/share/elasticsearch/data

   elastic-apm:
      image: docker.elastic.co/apm/apm-server:7.16.2
      container_name: elastic-apm
      ports:
        - "8200:8200"
      command: >
         apm-server -e
            -E apm-server.rum.enabled=true
            -E setup.kibana.host=kibana:5601
            -E setup.template.settings.index.number_of_replicas=0
            -E apm-server.kibana.enabled=true
            -E apm-server.kibana.host=kibana:5601
            -E output.elasticsearch.hosts=["elasticsearch:9200"]
      depends_on:
        - kibana
        - elasticsearch

   kibana:
      image: docker.elastic.co/kibana/kibana:7.16.2
      container_name: kibana
      ports:
         - "5601:5601"
      environment:
         ELASTICSEARCH_URL: http://elasticsearch:9200
         ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      depends_on:
         - elasticsearch

volumes:
  esdata:
    driver: local

networks:
   default:
      external: true
      name: appvideos