version: '3'

services:
   backend-appvideos:
      build: .
      container_name: backend-appvideos
      ports:
        - "3000:3000"
      volumes:
        - ".:/app"

   mysql:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      ports:
      - "3306:3306"
      volumes:
      - ".data:/var/lib/mysql"
      environment:
         MYSQL_USER: root
         MYSQL_ROOT_PASSWORD:
         MYSQL_DATABASE: appvideos

   phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.0-fpm-alpine
      ports:
      - "8080:80"
