version: '3.2'

services:
   backend-appvideos:
      build: .
      container_name: backend-appvideos
      volumes:
        - ".:/app"
      ports:
        - "3000:3000"
      depends_on:
        - mysql

   mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      ports:
        - "6033:3306"
      volumes:
        - "v_mysql:/var/lib/mysql"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: appvideos

   phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.1
      container_name: phpmyadmin
      restart: always
      ports:
        - "8081:80"
      environment:
        PMA_HOST: mysql
      depends_on:
        - mysql

   redis:
      image: redis:6.2.6-alpine
      container_name: redis
      ports:
        - "6379:6379"

volumes:
   v_mysql:
      external: true

networks:
   default:
      external: true
      name: appvideos