version: '3.2'

services:
   backend-appvideos:
      build: .
      container_name: backend-appvideos
      ports:
        - "3000:3000"
      volumes:
        - ".:/app"
      links:
        - "mysql"
   mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      ports:
      - "6033:3306"
      volumes:
      - ".data:/var/lib/mysql"
      environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: appvideos

   phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.1.1
      container_name: phpmyadmin
      restart: always
      environment:
         PMA_HOST: mysql
      depends_on:
      - mysql
      ports:
      - "8081:80"

# a senha e usuario é root
# caso queira usar o workbench, é so colocar localhost e a porta 6033. nao tem necessidade de usar o phpmyadmin como interface, então pode deletar as linhas