POST http://localhost:3000/usuario HTTP/1.1
content-type: application/json

{
    "nome": "euu",
    "email": "eu@mail.com",
    "senha": "eu.gmail.br.redes.com",
    "cpf": "17241770790"
}

###
GET http://localhost:3000/usuario HTTP/1.1