apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  env: |
     DB_USERNAME=root
     DB_PASSWORD=password
     DB_DATABASE=appvideos
     DB_DIALECT=mysql
     DB_HOST=mysql
     DB_USERNAME_TEST=test
     DB_PASSWORD_TEST=test
     DB_DATABASE_TEST=appvideos_test
     DB_DIALECT_TEST=sqlite

     REDIS_HOST=redis
     REDIS_PORT=6379

     API_PORT=3000
     JWT_SECRET=segredinho
     BCRYPT_SALT=10

     URL_AWS_S3=

     ELASTIC_APM_SERVICE_NAME=appvideos
     ELASTIC_APM_SERVER_URL=http://elastic-apm:8200
     ELASTIC_APM_ACTIVE=true

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - port: 3001
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
         - name: backend-container
           image: felippedeiro/backend-appvideos:v2.1
           volumeMounts:
             - name: backend-volume
               mountPath: /app/.env
               subPath: .env
           ports:
             - containerPort: 3000

      volumes:
        - name: backend-volume
          configMap:
            name: backend-configmap
            items:
              - key: env
                path: .env