name: CI-CD

on:
  push:
    branches: [develop]
   #  branches: [main]
#   pull_request:
   #  types: [opened, reopened]
   #  branches: [develop]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - run: npm ci

      - run: sh run-tests.sh

      - name: Check linting
        run: npm run lint

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

#   CD:
#     needs: [CI]
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2

#       - name: Docker Login
#         uses: docker/login-action@v1.10.0
#         with:
#           username: ${{ secrets.DOCKERHUB_USER }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}

#       - name: Docker Build and Push
#         uses: docker/build-push-action@v2.7.0
#         with:
#           context: ./
#           file: ./Dockerfile.prod
#           push: true
#           tags: |
#             felippedeiro/backend-appvideos:latest
#             felippedeiro/backend-appvideos:${{ github.run_number }}

      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "felippe-todo-tdd-cicd"
      #     heroku_email: ${{secrets.MEU_EMAIL}}